### ISSUE TITLE
Deployed application on Heroku

### ISSUE THREAD

**Issue by aagneyanNamboodiri** [aagneyanNamboodiri/wheel#15]
Deployed at : https://calm-island-40203.herokuapp.com/notes
Can be logged in using:
Username : oliver@example.com
Password : welcome

@yedhink Please review.

**Comment by yedhink** [comment]
@aagneyanNamboodiri I have provided you some reviews for your closed PRs. Once you address them lemme know over here.

**Comment by aagneyanNamboodiri** [comment]
@yedhink I have made the necessary changes to the code as mentioned in the previous PRs.

**Comment by yedhink** [comment]
@aagneyanNamboodiri Before assigning me for review should be doing a thorough review of all the functionalities from UI. Read https://handbook.neetokb.com/articles/git-and-github-essentials#self-review-process

Right now in your app I can add a note even if there is not assigned contact or tag, which is not right.

**Comment by aagneyanNamboodiri** [comment]
@yedhink 
I'm sorry for pinging you previously without pushing the changes to heroku. 
I have now made the necessary validation changes, as well as added a deletion UI, and have pushed all changes to heroku.

**Comment by yedhink** [comment]
@aagneyanNamboodiri I have added some more comments. Go through it and lemme know.

**Comment by aagneyanNamboodiri** [comment]
@yedhink 
I have made the necessary changes.

**Comment by yedhink** [comment]
@aagneyanNamboodiri 

- [x] The validation message inconsistency is not yet fixed everywhere. It's your responsibility to go through the whole app and verify where all changes ought to be made.
<img width="462" alt="image" src="https://user-images.githubusercontent.com/31244999/191190355-20f3002a-0b01-48e3-8585-cc9cd23d34d2.png">

- [x] `Settings` should be the last item in the sidemenu.
<img width="110" alt="image" src="https://user-images.githubusercontent.com/31244999/191190644-0d3d527d-0146-456f-b36e-06228c66924a.png">

Once you fix these issues, go ahead and mark this task as completed and continue with the next task.

**Comment by aagneyanNamboodiri** [comment]
I have done the fixes. 
Proceeding to close the issue.
